// SmartCrick AI — data.js
window.SC_DATA = (function(){

function makeSteps(title,secs,cat){
  const cores={
    confidence:'Recall your three most powerful performances. See yourself at your best. Your body knows how to perform. Trust it completely. Feel the confidence rising.',
    focus:'Narrow your attention to a single point. Let distracting thoughts float past like clouds. Return to your anchor. Pure, clean, locked-in focus is your natural state.',
    recovery:'Release the tension. Forgive what happened. Every great player bounces back. You are not your last performance. Reset. Refresh. Return stronger.',
    'pre-performance':'You have prepared. You are ready. Feel your body activate with controlled energy. Channel the nerves into sharpness. Your skills are ready to flow.',
    pressure:'Pressure is the weight of opportunity. You welcome it. Breathe into the challenge. The game slows down when your mind is still. You are the calmest person on the field.',
    visualization:'Paint a vivid, detailed mental image of perfect execution. See your technique. Feel the timing. Hear the sound. Your brain cannot tell the difference between a vivid image and reality.',
    'match-day-calm':'Today is the day. You are ready. Calm and energized. Focus on your process, not the result. Play one ball at a time. Trust your preparation.',
    'pro-mental':'Champions operate at this level — fully present, fully committed, fully trusting their game. There is no outcome — only process. Your mind is your greatest weapon.'
  };
  const b=Math.min(30,Math.floor(secs*.12));
  const main=Math.floor(secs*.65);
  const end=secs-b-Math.floor(secs*.12);
  return [
    {instruction:'Find a comfortable position. Close your eyes. Take three slow deep breaths. Let go of everything outside this session.',duration_seconds:b},
    {instruction:'This is your dedicated '+title+' session. Focus your full attention. Let the process work.',duration_seconds:Math.floor(secs*.1)},
    {instruction:cores[cat]||cores.focus,duration_seconds:main},
    {instruction:'As this session closes, take two slow deep breaths. Bring your awareness back. Carry what you have built into your next performance.',duration_seconds:end}
  ];
}
function mr(id,title,cat,secs,xp,premium){
  return {id,title,category:cat,duration_seconds:secs,xp_value:xp,is_premium:!!premium,
    description:Math.floor(secs/60)+'-minute '+cat.replace('-',' ')+' session.',
    steps:makeSteps(title,secs,cat)};
}

const jokes=[
'Why did the cricket team go to the bank? To get their bowler!',
'What do you call a cricket match in winter? A snow bowl!',
'Why dont cricketers ever get lost? They always follow the pitch!',
'Whats a cricketers favorite type of music? Swing!',
'Why did the batsman bring string to the match? To tie the score!',
'What do you call a cricket player whos always cold? A chilly fielder!',
'Whats a bowlers favorite subject? Spin class!',
'Why did the cricket bat go to the doctor? It had a bad case of the runs!',
'Why was the cricket stadium so hot? All the fans left!',
'What did the cricket ball say to the bat? Catch you later!',
'Why dont cricket players ever get hungry? Theyre always at the crease!',
'What did one cricket stump say to the other? Youre bailing on me!',
'Why cant cricketers ever win at chess? They always think its a draw!',
'What do you call a cricket player who becomes a chef? A batter!',
'What do you call a cricket match between cats? A meow-t!',
'Whats a batsmans favorite dessert? A sweet spot!',
'What do you call a cricketer with perfect hair? Well-groomed for the crease!',
'What do you call a cricket match with no boundaries? Very limited overs!',
'What do you call a fast bowler who can cook? A microwave — always heating things up!',
'What do you call a cricketer who loses every toss? A coin flipper with no luck!',
'Whats a spiders favorite fielding position? Silly mid-on, right in the web!',
'What do you call a cricketer whos always early? A pre-match overachiever!',
'What do you call a cricket match between accountants? A long-run affair!',
'What do you call a cricket bat with no willow? A real stick in the mud!',
'Did the cricket team open a bakery? They knew how to roll the dough!',
'Whats a cricketers favourite superhero? Captain No-Ball Man!',
'Why did the cricket coach bring scissors to training? To cut short the bad overs!',
'Why do cricket bowlers make great musicians? They always find the perfect pitch!',
'What did the cricket bat say at the end of the season? Im absolutely stumped!',
'Why did the fielder bring a compass? He kept losing his position at square leg!'
];

const facts=[
'The fastest recorded cricket ball was bowled at 161.3 km/h by Shoaib Akhtar!',
'The longest cricket match lasted 14 days between England and South Africa in 1939!',
'Sachin Tendulkar holds the record for most runs in international cricket with 34,357!',
'The first-ever Test match was played in 1877 between Australia and England!',
'The highest team score in ODI cricket is 498/4 by England against Netherlands!',
'Muttiah Muralitharan has the most Test wickets with 800!',
'The Cricket World Cup trophy weighs 11 kilograms!',
'The term duck comes from ducks egg because 0 looks like an egg!',
'India has won the Cricket World Cup twice: 1983 and 2011!',
'The fastest Test century was scored in 35 balls by AB de Villiers!',
'Cricket stumps are exactly 28 inches (71.1 cm) high!',
'Shane Warnes Ball of the Century spun 18 inches!',
'Brian Lara holds the record for highest Test innings: 400 not out!',
'The DRS Decision Review System was first used in 2008!',
'The fastest ODI century was scored in 31 balls by AB de Villiers!',
'Women's cricket was first played in 1745 in England!',
'The googly was invented by Bernard Bosanquet in 1900!',
'MS Dh0ni's lightning-fast stumping can happen in under 0.1 seconds!',
'Don Bradman's average of 99.94 is considered the greatest statistical achievement in sport.',
'Chris Gayle is the only player to hit a six off the first ball of a Test match!',
'A cricket ball weighs between 155.9 and 163 grams — precisely regulated.',
'India's 2011 World Cup win was watched by over 1 billion people live!',
'The first Cricket World Cup was held in England in 1975 and won by the West Indies.',
'The highest partnership in Test cricket is 624 runs by Jayawardene and Sangakkara.',
'T20 cricket was introduced in England in 2003 to attract younger audiences.',
'Cricket is the second most popular sport in the world after football!',
'A cricket ball swings more when one side is polished and the other is rough.',
'Sachin Tendulkar scored 100 international centuries — a record that may never be broken.',
'MS Dhoni invented the helicopter shot — a unique scoop-sweep innovation!',
'Jonty Rhodes revolutionized fielding standards in the 1990s with his athletic diving stops!'
];

const mentalRoutines=[
mr('m001','Micro Focus Burst','focus',180,35),
mr('m002','Physiological Sigh','recovery',180,35),
mr('m003','Reset Button','recovery',240,45),
mr('m004','Focus Next Ball','focus',240,45),
mr('m005','Morning Positivity Charge','confidence',240,40),
mr('m006','5-4-3-2-1 Grounding','match-day-calm',300,50),
mr('m007','Countdown to Clarity','focus',300,50),
mr('m008','Power Pose Reset','confidence',300,50),
mr('m009','Confidence Countdown','confidence',300,50),
mr('m010','10-Second Rule','pressure',300,50),
mr('m011','Celebrate Small Wins','confidence',300,50),
mr('m012','Focus Lock-In','focus',300,50),
mr('m013','2-Minute Warrior','confidence',300,50),
mr('m014','Micro-Win Review','confidence',300,50),
mr('m015','Self-Compassion Break','recovery',300,50),
mr('m016','Embracing Change','recovery',300,50),
mr('m017','Pre-Game Activation','pre-performance',300,50),
mr('m018','Gratitude for Journey','recovery',300,50),
mr('m019','Deep Calm Breathing','match-day-calm',300,50),
mr('m020','Positive Morning Anchor','confidence',300,50),
mr('m021','Mental Recovery Sprint','recovery',300,50),
mr('m022','Win the Morning','confidence',300,50),
mr('m023','Breathe Through Anger','pressure',300,50),
mr('m024','Team Player Mindset','confidence',300,50),
mr('m025','Reset After Duck','recovery',300,50),
mr('m026','Bowling Mindset Lock-In','focus',300,50),
mr('m027','Deep Breathing Anxiety','match-day-calm',300,50),
mr('m028','Gratitude Before Game','match-day-calm',300,50),
mr('m029','Worry Drawer','pressure',300,50),
mr('m030','Name Your Strength Challenge','confidence',300,50),
mr('m031','Task Isolation Protocol','focus',300,50),
mr('m032','Running Between Wickets','focus',300,50),
mr('m033','Five Senses Slow Down','match-day-calm',300,50),
mr('m034','Night Review 3 Good Things','recovery',300,50),
mr('m035','Celebrating Others Success','confidence',300,45),
mr('m036','4-7-8 Breath Lock','match-day-calm',360,50),
mr('m037','Self-Talk Rewrite','confidence',360,55),
mr('m038','Rejection Bounce','recovery',360,65),
mr('m039','Nervous Energy Converter','pre-performance',360,55),
mr('m040','Gratitude Anchor','match-day-calm',360,55),
mr('m041','Pre-Performance Calm','pre-performance',360,55),
mr('m042','Team Energy Alignment','confidence',360,55),
mr('m043','Present Moment Is Enough','focus',360,55),
mr('m044','Detox Breath','recovery',360,55),
mr('m045','Joy Audit','recovery',360,55),
mr('m046','Vocal Physical Presence','confidence',360,60),
mr('m047','Anchoring Peak State','pre-performance',360,65),
mr('m048','Grounding Instant Presence','focus',360,55),
mr('m049','Strategic Pause Activation','pressure',360,60),
mr('m050','Learning from Opponents','recovery',360,60),
mr('m051','Mental Highlight Reel','confidence',360,60),
mr('m052','Cultivating Beginners Mind','focus',360,60),
mr('m053','Deep Focus Anchor','focus',360,60),
mr('m054','Stillness Practice','match-day-calm',360,55),
mr('m055','Calm Before Storm','pre-performance',360,55),
mr('m056','Laser Focus Activation','focus',360,55),
mr('m057','Gratitude Perspective Shift','recovery',360,55),
mr('m058','Bounce-Back Faster','recovery',360,60),
mr('m059','Focus What You Control','pressure',360,55),
mr('m060','Optimism Training','confidence',360,55),
mr('m061','Mindful Performance Reset','focus',360,55),
mr('m062','Dealing with Criticism','recovery',360,55),
mr('m063','Dealing Nerves Batting','pre-performance',360,60),
mr('m064','Accountability Mirror','confidence',360,60),
mr('m065','Cold Pressure Simulation','pressure',360,75),
mr('m066','1% Better Mindset','focus',360,55),
mr('m067','Sensory Narrowing','focus',360,60),
mr('m068','Trusted Teammate Lens','confidence',360,55),
mr('m069','Pressure Release Valve','pressure',360,55),
mr('m070','Breathing Through Batting Collapse','pressure',360,65),
mr('m071','Environmental Intention Setting','pre-performance',360,55),
mr('m072','Compassionate Coaching Voice','recovery',360,55),
mr('m073','Catching Under Pressure','pressure',360,60),
mr('m074','Discipline Contract','focus',360,60),
mr('m075','Craving the Challenge','confidence',360,65),
mr('m076','Separating Result from Worth','recovery',360,55),
mr('m077','Possibility Scanner','confidence',360,55),
mr('m078','Believing in Tomorrow','recovery',360,55),
mr('m079','Calm Competitor','pressure',360,60),
mr('m080','Motivation Without Mood','confidence',360,60),
mr('m081','Pressure Is Information','pressure',360,60),
mr('m082','Positive Pressure Partnership','pressure',360,55),
mr('m083','Long View Perspective','recovery',360,55),
mr('m084','Distraction Shield','focus',420,65),
mr('m085','Evidence of Strength','confidence',420,60),
mr('m086','Affirmation Immersion','confidence',420,60),
mr('m087','Own the Room','confidence',420,65),
mr('m088','Pressure Is Privilege','pressure',420,65),
mr('m089','Let It Go Protocol','recovery',420,60),
mr('m090','Breathe Through Bad Day','recovery',420,60),
mr('m091','Failure as Feedback','recovery',420,60),
mr('m092','Best Self Morning','confidence',420,60),
mr('m093','Game Day Activation','pre-performance',420,65),
mr('m094','Letting Go of Last Time','recovery',420,65),
mr('m095','Dealing Crowd Environment','pressure',420,65),
mr('m096','Process Over Result','focus',420,65),
mr('m097','Evening Review Unwind','recovery',420,60),
mr('m098','Emotional Intelligence Check-In','recovery',420,65),
mr('m099','Discipline Over Motivation','focus',420,65),
mr('m100','Relationship with Effort','confidence',420,65),
mr('m101','Silent Minute Protocol','focus',420,65),
mr('m102','Abundance Mindset Shift','confidence',420,65),
mr('m103','Owning Your Uniqueness','confidence',420,65),
mr('m104','Competition as Fuel','pressure',420,65),
mr('m105','Morning Clarity Protocol','focus',420,60),
mr('m106','Embrace the Discomfort','pressure',420,70),
mr('m107','Closing the Loop','recovery',420,65),
mr('m108','Noise Cancellation Focus','focus',420,70),
mr('m109','Embrace the Arena','pre-performance',420,65),
mr('m110','Energy Source Identification','confidence',420,60),
mr('m111','What If Neutralizer','pressure',420,65),
mr('m112','Future-Pacing Success','visualization',420,65),
mr('m113','Decision Clarity Under Pressure','pressure',420,70),
mr('m114','Responding to Unfairness','recovery',420,70),
mr('m115','Handling Unplayable Ball','recovery',420,70),
mr('m116','Bowling Under Pressure','pressure',420,65),
mr('m117','Fuel Your Fire','confidence',420,60),
mr('m118','Rediscovering Your Why','confidence',420,65),
mr('m119','Anxiety Dissolve Protocol','match-day-calm',420,65),
mr('m120','Deep Recovery Breathing','recovery',420,65),
mr('m121','Motivational Momentum Builder','confidence',420,65),
mr('m122','Deep Pressure Release','pressure',420,60),
mr('m123','Believe It Session','confidence',420,65),
mr('m124','Beat Fear of Failure','confidence',420,65),
mr('m125','Body Scan Energy Reset','recovery',420,60),
mr('m126','Overcome Overthinking','focus',420,65),
mr('m127','Worst-Case Freedom','pressure',420,65),
mr('m128','Confidence Through Preparation','confidence',420,60),
mr('m129','Performing for Love of It','confidence',420,60),
mr('m130','Repair After a Row','recovery',420,65),
mr('m131','Fielding Brilliance Rehearsal','visualization',420,65),
mr('m132','Bounce-Back Blueprint','recovery',420,65),
mr('m133','Inner Lake','match-day-calm',420,60),
mr('m134','Positive Reframe Machine','recovery',420,65),
mr('m135','4-7-8 Breath Reset','match-day-calm',420,60),
mr('m136','Power of No Excuses','confidence',420,70),
mr('m137','Competitors Code','pressure',420,65),
mr('m138','Mind Over Fatigue','pressure',420,75),
mr('m139','Trusting Instinct','focus',420,65),
mr('m140','Single-Point Focus Drill','focus',480,55),
mr('m141','Attention Anchor','focus',480,65),
mr('m142','Inner Champion','confidence',480,65),
mr('m143','Courage Over Comfort','confidence',480,70),
mr('m144','Storm and Stillness','pressure',480,70),
mr('m145','Adversity as Advantage','recovery',480,70),
mr('m146','Self-Compassion Practice','recovery',480,65),
mr('m147','Emotional Drain Release','recovery',480,70),
mr('m148','Boundaries Burnout Prevention','recovery',480,70),
mr('m149','Master Skill Replay','visualization',480,70),
mr('m150','Future Memory','visualization',480,70),
mr('m151','Obstacle Visualisation','visualization',480,70),
mr('m152','Calm Under Pressure Visualisation','visualization',480,70),
mr('m153','Post-Performance Review','recovery',480,70),
mr('m154','Composed Under Fire','pressure',480,80),
mr('m155','Morning Mindset Ritual','confidence',480,65),
mr('m156','Stress Inoculation','pressure',480,80),
mr('m157','Resilience Story','recovery',480,70),
mr('m158','Patience Long-Game Thinking','focus',480,70),
mr('m159','Decision Maker','pressure',480,70),
mr('m160','Under the Microscope','pressure',480,80),
mr('m161','Why Engine','confidence',480,70),
mr('m162','Champions Setback','recovery',480,70),
mr('m163','Box Breathing Method','match-day-calm',480,65),
mr('m164','Imposter Dissolve','confidence',480,70),
mr('m165','Releasing Expectations','pressure',480,70),
mr('m166','Breaking the Mental Block','focus',480,80),
mr('m167','Freedom from Judgment','pressure',480,70),
mr('m168','Releasing Outcome Attachment','focus',480,75),
mr('m169','Inner Critic Translator','recovery',480,70),
mr('m170','Growth Mindset Fuel','confidence',480,70),
mr('m171','Decision-Making Clarity','focus',480,70),
mr('m172','Active Listening for Insight','focus',480,70),
mr('m173','Vision Board Visualization','visualization',480,70),
mr('m174','Batting Through Hard Session','pressure',480,70),
mr('m175','Staying Calm Under Fire','pressure',480,70),
mr('m176','Unbreakable Mindset','confidence',480,80),
mr('m177','Positive Self-Image Builder','confidence',480,70),
mr('m178','Quiet the Noise','focus',480,70),
mr('m179','Comeback Mindset','recovery',480,70),
mr('m180','Sleep Better Tonight','recovery',480,60),
mr('m181','Handling Losing Streak','recovery',480,70),
mr('m182','Post-Game Emotional Release','recovery',480,70),
mr('m183','Winning the Inner Battle','confidence',480,70),
mr('m184','Pre-Match Ritual Builder','pre-performance',480,70),
mr('m185','Breath as Anchor','match-day-calm',480,60),
mr('m186','Pressure Rehearsal Crucial Over','pressure',480,80),
mr('m187','Decompression Zone','recovery',480,65),
mr('m188','Thought Labeling Practice','focus',480,65),
mr('m189','Failure Inventory','recovery',480,70),
mr('m190','Box Breathing Navy Seal','pressure',480,65),
mr('m191','Processing Disappointment','recovery',480,70),
mr('m192','Finding Flow Through Challenge','focus',480,75),
mr('m193','Staying Positive After Being Dropped','recovery',480,70),
mr('m194','Radical Acceptance','recovery',480,70),
mr('m195','Developing Elite Patience','focus',480,75),
mr('m196','Body Scan Focus Reset','focus',540,60),
mr('m197','Comparison Detox','confidence',540,70),
mr('m198','Unshakeable Foundation','confidence',540,75),
mr('m199','Forgiveness Forward Movement','recovery',540,80),
mr('m200','Perfect Performance','visualization',540,75),
mr('m201','Healing Visualisation','recovery',540,70),
mr('m202','Morning of Big Day','pre-performance',540,75),
mr('m203','Deep Work Session Primer','focus',540,70),
mr('m204','Process Film','visualization',540,75),
mr('m205','Grief Permission','recovery',540,80),
mr('m206','10 Years Forward','visualization',540,75),
mr('m207','Pre-Sleep Mental Shutdown','recovery',540,70),
mr('m208','Choke-Proof Preparation','pressure',540,80),
mr('m209','Life Balance Audit','recovery',540,75),
mr('m210','Post-Performance Debrief','recovery',540,70),
mr('m211','Patience Cultivation','focus',540,80),
mr('m212','Detaching from Perfectionism','recovery',540,80),
mr('m213','Champions Routine','pre-performance',540,75),
mr('m214','Full Body Relaxation','recovery',540,65),
mr('m215','Visualization for Skill Building','visualization',540,75),
mr('m216','Identity-Based Goal Setting','confidence',540,75),
mr('m217','Comeback Innings','recovery',540,75),
mr('m218','Letter to Future Self','visualization',540,75),
mr('m219','Pressure Ladder','pressure',540,80),
mr('m220','Flow State Trigger','focus',600,75),
mr('m221','Deep Work Preparation','focus',600,75),
mr('m222','Mental Toughness Builder','pressure',600,85),
mr('m223','High Stakes Rehearsal','pressure',600,85),
mr('m224','Sleep Recovery Reset','recovery',600,70),
mr('m225','Intentional Rest','recovery',600,70),
mr('m226','Goal Movie','visualization',600,80),
mr('m227','Champion Mindset Simulation','pro-mental',600,85),
mr('m228','New Identity Visualisation','visualization',600,85),
mr('m229','Deliberate Practice Mindset','pro-mental',600,100,true),
mr('m230','Mastery Over Perfection','pro-mental',600,100,true),
mr('m231','Sensory Performance Blueprint','visualization',600,85),
mr('m232','Vivid Goal Map','visualization',600,80),
mr('m233','Recharge Internal Battery','recovery',600,75),
mr('m234','Pre-Tournament Mind Lock','pre-performance',600,80),
mr('m235','Performance Rituals Design','pro-mental',660,105,true),
mr('m236','Psychological Safety Risk-Taking','pro-mental',660,105,true),
mr('m237','Identity Leverage','pro-mental',720,110,true),
mr('m238','Zone of Genius Activation','pro-mental',720,110,true),
mr('m239','Elite Competitor Analysis','pro-mental',720,110,true),
mr('m240','Inner Dialogue Mastery','pro-mental',720,110,true),
mr('m241','Elite Endurance Mindset','pro-mental',720,110,true),
mr('m242','Flow State Architecture','pro-mental',900,120,true)
];

const drills=[
{id:'d001',title:'Cover Drive Mastery',category:'Batting',difficulty:'Beginner',duration_minutes:15,xp_value:60,is_premium:false,description:'Perfect the cover drive.',instructions:'Stand side-on. Step forward. Drive through the line. Follow through high toward cover.',tips:['Head over the ball','Front elbow toward mid-on','Watch the ball onto the bat']},
{id:'d002',title:'Pull Shot Power',category:'Batting',difficulty:'Intermediate',duration_minutes:20,xp_value:80,is_premium:false,description:'Powerful pull shot against short-pitched bowling.',instructions:'Rock back early. Pivot on back foot. Whip through the line toward mid-wicket.',tips:['Get in position early','Stay tall on back foot','Roll wrists at contact']},
{id:'d003',title:'Straight Drive Precision',category:'Batting',difficulty:'Beginner',duration_minutes:15,xp_value:60,is_premium:false,description:'Hit straight back down the ground.',instructions:'Watch the full delivery. Step in. Present full bat face. Drive through the V.',tips:['Head still at contact','High elbow on backlift','Follow through toward bowler']},
{id:'d004',title:'Cut Shot Technique',category:'Batting',difficulty:'Intermediate',duration_minutes:20,xp_value:80,is_premium:false,description:'Attack short-wide deliveries with cut shot.',instructions:'Identify short wide ball. Rock back across. Chop down toward point.',tips:['Give yourself room to cut','Keep shot down','Watch ball closely']},
{id:'d005',title:'Sweep Shot Drills',category:'Batting',difficulty:'Intermediate',duration_minutes:20,xp_value:80,is_premium:false,description:'Master the sweep against spin bowling.',instructions:'Get to the pitch. Get down low. Sweep toward fine leg or square leg.',tips:['Commit to shot','Protect stumps with pad','Vary sweep and slog sweep']},
{id:'d006',title:'Defensive Technique',category:'Batting',difficulty:'Beginner',duration_minutes:15,xp_value:50,is_premium:false,description:'Build an unbreakable defensive foundation.',instructions:'Get behind the line. Present bat and pad together. Soft hands.',tips:['Lean front foot for length balls','Relax hands at contact','Keep bat angle closed']},
{id:'d007',title:'Flick Shot Perfection',category:'Batting',difficulty:'Advanced',duration_minutes:25,xp_value:100,is_premium:false,description:'Master the on-side flick.',instructions:'Ball on leg stump. Open hips early. Flick wrists at contact.',tips:['Stay balanced','Use wrist not arm','Get inside the line']},
{id:'d008',title:'Slog Sweep for T20',category:'Batting',difficulty:'Advanced',duration_minutes:20,xp_value:120,is_premium:true,description:'Aggressive hitting weapon against spinners.',instructions:'Get to the pitch. Front knee down. Hit over mid-wicket with power.',tips:['Choose the right ball','Get under it','Use depth of crease']},
{id:'d009',title:'Running Between Wickets',category:'Batting',difficulty:'Beginner',duration_minutes:20,xp_value:70,is_premium:false,description:'Communication and speed running.',instructions:'Call early: yes no wait. Sprint and ground the bat. Back up constantly.',tips:['Loud clear calls','Turn with bat in hand','Always back up']},
{id:'d010',title:'Yorker Defense',category:'Batting',difficulty:'Advanced',duration_minutes:25,xp_value:110,is_premium:false,description:'Survive and score off yorkers.',instructions:'Read release point. Get bat down early. Dig out along ground. Use the crease.',tips:['Read the wrist','Get bat down fast','Use depth of crease']},
{id:'d011',title:'Outswing Basics',category:'Bowling',difficulty:'Beginner',duration_minutes:20,xp_value:70,is_premium:false,description:'Swing the ball away from right-handed batsman.',instructions:'Seam toward fine slip. High wrist. Bowl full length.',tips:['Shine one side','Seam upright at release','Hit good length']},
{id:'d012',title:'Inswing Bowling',category:'Bowling',difficulty:'Intermediate',duration_minutes:20,xp_value:80,is_premium:false,description:'Bring ball into right-handed batsman.',instructions:'Seam toward fine leg. Wrist rotates slightly. Fuller length.',tips:['Bowl full','Target gap between bat and pad','Seam upright']},
{id:'d013',title:'Leg Spin Grips & Action',category:'Bowling',difficulty:'Intermediate',duration_minutes:25,xp_value:90,is_premium:false,description:'Master the basic leg spin delivery.',instructions:'Third finger on seam. Cock wrist. Spin from third finger.',tips:['Overspin for dip','Consistent run-up','Rip third finger hard']},
{id:'d014',title:'Off Spin Fundamentals',category:'Bowling',difficulty:'Beginner',duration_minutes:20,xp_value:70,is_premium:false,description:'Develop consistent off spin.',instructions:'Grip across seam. Turn ball from right to left. Flight it up.',tips:['Use fingers not wrist','Drift with wind','Vary pace with flighted deliveries']},
{id:'d015',title:'Yorker Accuracy Drill',category:'Bowling',difficulty:'Advanced',duration_minutes:30,xp_value:110,is_premium:false,description:'Hit the yorker length repeatedly under pressure.',instructions:'Place cone at yorker zone. Bowl full. Aim to hit cone. Repeat 30 balls.',tips:['Think: hit the feet','Run in hard','Use at death overs']},
{id:'d016',title:'Slower Ball Variations',category:'Bowling',difficulty:'Advanced',duration_minutes:25,xp_value:120,is_premium:true,description:'Add cutters and slower balls.',instructions:'Off-cutter: cut finger across seam. Leg-cutter: opposite way. Same action.',tips:['Disguise is everything','One variation at a time','Bowl at stumps']},
{id:'d017',title:'Reverse Swing',category:'Bowling',difficulty:'Advanced',duration_minutes:30,xp_value:130,is_premium:true,description:'Master reverse swing with old ball.',instructions:'Old ball shiny side facing batsman. Bowl full and fast. Target off stump.',tips:['40+ overs old ball','Bowl fuller','Hard seam upright']},
{id:'d018',title:'Line & Length Consistency',category:'Bowling',difficulty:'Beginner',duration_minutes:20,xp_value:60,is_premium:false,description:'Bowl 30 balls on consistent line and length.',instructions:'Mark good-length zone and 4th-stump line. Bowl aiming to hit both zones.',tips:['Same run-up every ball','Watch where ball pitches','Adjust release height']},
{id:'d019',title:'Googly Bowling',category:'Bowling',difficulty:'Advanced',duration_minutes:25,xp_value:130,is_premium:true,description:'Develop the mystery googly.',instructions:'Leg spin grip. Rotate wrist over the top. Ball spins other way.',tips:['Disguise wrist position','Bowl wide of off stump','Master leg break first']},
{id:'d020',title:'Death Bowling Masterclass',category:'Bowling',difficulty:'Advanced',duration_minutes:30,xp_value:140,is_premium:true,description:'Bowl final overs in T20 under pressure.',instructions:'Mix yorkers slower balls and bouncers. Vary pace and length every ball.',tips:['Never bowl same ball twice','Wide yorkers','Bouncer as surprise']},
{id:'d021',title:'Ground Fielding Basics',category:'Fielding',difficulty:'Beginner',duration_minutes:15,xp_value:50,is_premium:false,description:'Long-barrier and clean pick-up.',instructions:'Get side-on. Long leg back. Scoop ball into cupped hands.',tips:['Body behind ball','Watch into hands','Quick release after pick-up']},
{id:'d022',title:'Catching High Balls',category:'Fielding',difficulty:'Intermediate',duration_minutes:20,xp_value:80,is_premium:false,description:'Take high skiers with confidence.',instructions:'Call early. Position under ball. Cup hands above face. Soft hands.',tips:['Call loud: I HAVE IT','Move feet early','Steady platform']},
{id:'d023',title:'Diving Stops & Saves',category:'Fielding',difficulty:'Advanced',duration_minutes:25,xp_value:100,is_premium:false,description:'Superman dive to save boundaries.',instructions:'React fast. Full dive. Get body behind ball. Get up quickly.',tips:['Commit to dive','Land on hip not elbow','Train both sides']},
{id:'d024',title:'Flat Throw to Stumps',category:'Fielding',difficulty:'Intermediate',duration_minutes:20,xp_value:80,is_premium:false,description:'Accurate flat throws to either end.',instructions:'Pick up clean. Side-on to target. Overarm throw. Aim at top of stumps.',tips:['Follow through toward target','Use lead shoulder','Practice 20m and 30m']},
{id:'d025',title:'Slip Catching Drill',category:'Fielding',difficulty:'Intermediate',duration_minutes:20,xp_value:90,is_premium:false,description:'React to edges and take clean slip catches.',instructions:'Ready position — knees bent. Watch the bat. React to edge. Soft hands.',tips:['Move after ball not before','Cup hands and give','Stay low']},
{id:'d026',title:'Boundary Saving',category:'Fielding',difficulty:'Intermediate',duration_minutes:20,xp_value:80,is_premium:false,description:'Stop balls at the boundary.',instructions:'Track ball to boundary. Step over rope. Flick ball back before feet land outside.',tips:['Watch the rope','Lean back into field','Quick hand action']},
{id:'d027',title:'Inner Circle Fielding',category:'Fielding',difficulty:'Beginner',duration_minutes:15,xp_value:60,is_premium:false,description:'Save singles inside 30-yard circle.',instructions:'Aggressive ready position. Attack the ball. Get low. Quick throw.',tips:['Cut off singles','Attack not retreat','Stay on toes']},
{id:'d028',title:'Run Out Techniques',category:'Fielding',difficulty:'Intermediate',duration_minutes:20,xp_value:90,is_premium:false,description:'Improve run out success rate.',instructions:'Pick up quick. Throw with accuracy. Aim at base of stumps.',tips:['Hit stumps not keeper','Underarm for close run outs','One stump wide safety margin']},
{id:'d029',title:'Keeper Stance & Movement',category:'Wicketkeeping',difficulty:'Beginner',duration_minutes:15,xp_value:60,is_premium:false,description:'Perfect keeping stance.',instructions:'Weight on toes. Hands out front. Side-step with ball. Stay low.',tips:['Never cross feet','Soft hands','Move with ball early']},
{id:'d030',title:'Standing Up to Spinners',category:'Wicketkeeping',difficulty:'Advanced',duration_minutes:25,xp_value:120,is_premium:true,description:'Keep wicket up to stumps against spin.',instructions:'Stand close to stumps. Watch pitch of ball. React to spin direction.',tips:['Take ball late','Give yourself room','Ready for stumping always']},
{id:'d031',title:'Cricket Sprint Training',category:'Fitness',difficulty:'Beginner',duration_minutes:20,xp_value:70,is_premium:false,description:'Build explosive sprint speed.',instructions:'Sprint 22 yards 10 times. Rest 30s. Focus on first step explosion.',tips:['Drive the arms','Stay low first 5 metres','Push off back foot']},
{id:'d032',title:'Footwork Ladder Drills',category:'Fitness',difficulty:'Intermediate',duration_minutes:20,xp_value:80,is_premium:false,description:'Rapid footwork with agility ladder.',instructions:'Two feet in each rung. One foot each. Lateral shuffles. 5 passes.',tips:['Stay on toes','Arms drive legs','Increase speed each pass']},
{id:'d033',title:'Core Stability',category:'Fitness',difficulty:'Beginner',duration_minutes:15,xp_value:60,is_premium:false,description:'Core strength for all cricket skills.',instructions:'Plank 3x30s. Side plank 2x20s. Dead bug 3x10. Bird dog 3x10.',tips:['Brace core throughout','Never let hips sag','Breathe steadily']},
{id:'d034',title:'Shoulder Strength & Mobility',category:'Fitness',difficulty:'Intermediate',duration_minutes:20,xp_value:80,is_premium:false,description:'Protect shoulder and build power.',instructions:'Band pull-aparts 3x15. Face pulls 3x12. External rotations 3x15.',tips:['No heavy weights','Focus on form','Include in every session']},
{id:'d035',title:'Explosive Leg Power',category:'Fitness',difficulty:'Advanced',duration_minutes:25,xp_value:100,is_premium:false,description:'Leg power for batting bowling and fielding.',instructions:'Box jumps 4x8. Jump squats 3x10. Single-leg bounds 3x6. Sprint starts 5x30m.',tips:['Land softly','Full hip extension on take-off','Rest 90s between explosive sets']},
{id:'d036',title:'Pressure Batting Simulation',category:'Mental',difficulty:'Intermediate',duration_minutes:20,xp_value:90,is_premium:false,description:'Bat under simulated match pressure.',instructions:'Last 5 overs. Need 30 runs. Face 20 balls. Stay process-focused.',tips:['One ball at a time','Between-ball routine','Celebrate good balls faced']},
{id:'d037',title:'Visualization Batting',category:'Mental',difficulty:'Beginner',duration_minutes:15,xp_value:60,is_premium:false,description:'Mentally rehearse your best batting.',instructions:'Close eyes. Picture walking to crease. Face 10 deliveries in your mind. Play each perfectly.',tips:['Be vivid and specific','Include crowd noise','Feel the bat in your hands']},
{id:'d038',title:'Reset After Wicket',category:'Mental',difficulty:'Intermediate',duration_minutes:10,xp_value:70,is_premium:false,description:'Mental reset after losing your wicket.',instructions:'3 deep breaths. Write what happened. Identify one learning. Commit to next innings.',tips:['No self-blame','Focus forward','Keep a match journal']},
{id:'d039',title:'T20 Power Hitting',category:'Batting',difficulty:'Advanced',duration_minutes:25,xp_value:110,is_premium:false,description:'Maximize boundary hitting in T20.',instructions:'Face throwdowns on good length. Aim to clear mid-wicket and long-on. 20 balls per set.',tips:['Get to pitch of ball','Stay balanced','Clear front leg for width']},
{id:'d040',title:'Reverse Sweep & Ramp',category:'Batting',difficulty:'Advanced',duration_minutes:20,xp_value:130,is_premium:true,description:'Ramp and reverse sweep for T20.',instructions:'Ramp: step outside off stump. Reverse sweep: convert at last moment.',tips:['Use against full toss or good length','Practice half pace first','Watch ball late']},
{id:'d041',title:'Leg Glance & Tickle',category:'Batting',difficulty:'Beginner',duration_minutes:15,xp_value:60,is_premium:false,description:'Easy runs on leg side with deflections.',instructions:'Ball on leg stump. Angle bat face. Let ball glance toward fine leg.',tips:['Less is more','Let ball do the work','Stay behind the line']},
{id:'d042',title:'Lofted Drive Over Mid-On',category:'Batting',difficulty:'Intermediate',duration_minutes:20,xp_value:85,is_premium:false,description:'Hit spinner over the top with control.',instructions:'Pick the full delivery. Get under ball. Full swing with high follow-through.',tips:['Get to pitch of ball','Open body slightly','Swing through contact']},
{id:'d043',title:'Playing Swing Bowling',category:'Batting',difficulty:'Intermediate',duration_minutes:20,xp_value:85,is_premium:false,description:'Handle inswing and outswing.',instructions:'Play late against swing. Soft top hand. Bat behind pad for inswinger.',tips:['Watch seam out of hand','Play straight','Soft hands reduce edges']},
{id:'d044',title:'Batting Against Spin',category:'Batting',difficulty:'Intermediate',duration_minutes:25,xp_value:90,is_premium:false,description:'Use feet and sweep against quality spin.',instructions:'Use your crease. Get to pitch or go back. Mix sweep with defensive push.',tips:['Read hand at release','Use crease wisely','Sweep the straight ones']},
{id:'d045',title:'Bouncer Strategy',category:'Bowling',difficulty:'Intermediate',duration_minutes:20,xp_value:90,is_premium:false,description:'Use bouncer as a weapon.',instructions:'Bowl short of length. Target outside shoulder. Follow with full ball.',tips:['Aim at armpit','Steep and straight','Unsettle then target stumps']},
{id:'d046',title:'Seam Bowling Consistency',category:'Bowling',difficulty:'Beginner',duration_minutes:20,xp_value:65,is_premium:false,description:'Bowl with upright seam for movement.',instructions:'Hold across seam. Keep seam upright. Roll fingers over top at release.',tips:['Seam upright = movement','Bowl full enough','High action helps']},
{id:'d047',title:'Bowling to Plans',category:'Bowling',difficulty:'Advanced',duration_minutes:25,xp_value:120,is_premium:true,description:'Target batsman weaknesses with clear bowling plan.',instructions:'Identify weakness. Design 6-ball plan. Bowl to it without deviation.',tips:['Set the trap early','Two in a row to establish pattern','Vary pace not line']},
{id:'d048',title:'Keeper Down Leg Side',category:'Wicketkeeping',difficulty:'Intermediate',duration_minutes:20,xp_value:85,is_premium:false,description:'Take balls angled down leg side.',instructions:'Quick side-step. Gloves together. Catch ball outside left leg.',tips:['Soft hands','Weight on toes','Stay low']},
{id:'d049',title:'Net Session Discipline',category:'Mental',difficulty:'Beginner',duration_minutes:20,xp_value:60,is_premium:false,description:'Get the most out of net sessions.',instructions:'Set goal before you go in. Play proper match shots. Evaluate after 10 balls.',tips:['Quality over quantity','Specific goal','Get uncomfortable deliberately']},
{id:'d050',title:'Match Simulation',category:'Mental',difficulty:'Advanced',duration_minutes:30,xp_value:130,is_premium:true,description:'Replicate match conditions in training.',instructions:'Set a scenario. Last over needed. Batting first ball. Make it count.',tips:['Raise the stakes','Record yourself','Get a team to field']},
{id:'d051',title:'Switch Hit Technique',category:'Batting',difficulty:'Advanced',duration_minutes:20,xp_value:140,is_premium:true,description:'The audacious switch hit.',instructions:'Change hands and stance at last moment. Hit to the opposite side.',tips:['Practice in slow motion','Pick a full delivery','Commit fully']},
{id:'d052',title:'Scoop Shot Ramp',category:'Batting',difficulty:'Advanced',duration_minutes:20,xp_value:110,is_premium:false,description:'Ramp over the keeper for six.',instructions:'Open stance. Get inside line. Scoop over fine leg. Full face.',tips:['Full and straight ball','Best against pace','Watch till contact']},
{id:'d053',title:'Long Barrier Fielding',category:'Fielding',difficulty:'Beginner',duration_minutes:15,xp_value:50,is_premium:false,description:'Safest way to stop ball on boundary.',instructions:'Turn side-on. Drop one knee. Cup hands. Let ball roll in.',tips:['Never rush','Body behind ball','Two hands always']},
{id:'d054',title:'Outfield Sprinting & Sliding',category:'Fielding',difficulty:'Intermediate',duration_minutes:20,xp_value:80,is_premium:false,description:'Aggressive outfield running and sliding.',instructions:'Sprint full speed at ball. Slide on hip. Pick up and throw.',tips:['Slide on hip not knee','Keep ball in sight','Throw from ground if needed']},
{id:'d055',title:'Bowling Run-Up Consistency',category:'Bowling',difficulty:'Beginner',duration_minutes:15,xp_value:60,is_premium:false,description:'Build a repeatable rhythmical run-up.',instructions:'Mark approach. Count steps. Practice without ball 20 times.',tips:['Measure from bowling crease','Accelerate into crease','Same footfall every time']},
{id:'d056',title:'Power Play Batting',category:'Batting',difficulty:'Intermediate',duration_minutes:20,xp_value:85,is_premium:false,description:'Maximize first 6 overs.',instructions:'Play attacking cricket. Use the gaps. Clear inner ring. Convert 1s to 2s.',tips:['Pick gaps not over fielders','Use powerplay field','Stay positive']},
{id:'d057',title:'Middle Overs Batting',category:'Batting',difficulty:'Intermediate',duration_minutes:20,xp_value:80,is_premium:false,description:'Build innings and accelerate in overs 7-15.',instructions:'Set platform first 5 balls. Hit the sixth. Rotate strike constantly.',tips:['Never 4 balls without run','Target spinner you fancy','Singles are not failures']},
{id:'d058',title:'Catching Practice Pairs',category:'Fielding',difficulty:'Beginner',duration_minutes:15,xp_value:55,is_premium:false,description:'Build catching reflexes with partner.',instructions:'Stand 5m apart. Throw underarm at various heights. 20 each. Progress to 10m.',tips:['Two hands unless forced','Watch it in','Soft hands']},
{id:'d059',title:'Wrist Spin Variations',category:'Bowling',difficulty:'Advanced',duration_minutes:25,xp_value:130,is_premium:true,description:'Add flipper and topspinner.',instructions:'Flipper: squeeze from under hand. Topspinner: bowl over the top.',tips:['Master leg break first','Practice slowly','Use to deceive not replace']},
{id:'d060',title:'Grip Pressure & Bat Speed',category:'Batting',difficulty:'Intermediate',duration_minutes:15,xp_value:75,is_premium:false,description:'Light grip means fast hands.',instructions:'Hold bat at 30% pressure. Shadow-bat 50 strokes. Focus on wrist snap.',tips:['Light top hand','Tight at contact only','Feel the bat whip through']}
];

const workouts=[
{id:'w001',name:'Back Strength Builder',level:'intermediate',exercises_count:5,duration:'15-20',xp_value:140,target:'back',category:'strength'},
{id:'w002',name:'Arms Beginner Blast',level:'beginner',exercises_count:4,duration:'10-15',xp_value:85,target:'arms',category:'strength'},
{id:'w003',name:'Full Body Power Pro',level:'pro',exercises_count:6,duration:'25+',xp_value:320,target:'full body',category:'power'},
{id:'w004',name:'Chest Sculpt Starter',level:'beginner',exercises_count:5,duration:'10-15',xp_value:90,target:'chest',category:'strength'},
{id:'w005',name:'Fat Burn HIIT 20',level:'advanced',exercises_count:6,duration:'20-25',xp_value:210,target:'full body',category:'cardio'},
{id:'w006',name:'Back Intermediate Strength',level:'intermediate',exercises_count:4,duration:'15-20',xp_value:135,target:'back',category:'strength'},
{id:'w007',name:'Total Body Toning',level:'beginner',exercises_count:5,duration:'15-20',xp_value:100,target:'full body',category:'toning'},
{id:'w008',name:'Shoulder Strength Supreme',level:'advanced',exercises_count:5,duration:'15-20',xp_value:170,target:'shoulders',category:'strength'},
{id:'w009',name:'Arms & Core Power',level:'intermediate',exercises_count:4,duration:'10-15',xp_value:110,target:'arms',category:'strength'},
{id:'w010',name:'Shoulders Intermediate Sculpt',level:'intermediate',exercises_count:4,duration:'15-20',xp_value:140,target:'shoulders',category:'strength'},
{id:'w011',name:'Chest Intermediate Build',level:'intermediate',exercises_count:4,duration:'15-20',xp_value:145,target:'chest',category:'strength'},
{id:'w012',name:'Core Crusher Advanced',level:'advanced',exercises_count:5,duration:'15-20',xp_value:180,target:'core',category:'strength'},
{id:'w013',name:'Legs Beginner Strength',level:'beginner',exercises_count:4,duration:'10-15',xp_value:90,target:'legs',category:'strength'},
{id:'w014',name:'Shoulder Mobility Warm-Up',level:'beginner',exercises_count:4,duration:'<10',xp_value:60,target:'shoulders',category:'mobility'},
{id:'w015',name:'Back & Posture Fix',level:'beginner',exercises_count:4,duration:'10-15',xp_value:85,target:'back',category:'posture'},
{id:'w016',name:'Shoulders Elite Pro',level:'pro',exercises_count:5,duration:'20-25',xp_value:270,target:'shoulders',category:'power'},
{id:'w017',name:'Legs Advanced Blast',level:'advanced',exercises_count:5,duration:'20-25',xp_value:190,target:'legs',category:'strength'},
{id:'w018',name:'Legs Intermediate Circuit',level:'intermediate',exercises_count:5,duration:'20-25',xp_value:165,target:'legs',category:'circuit'},
{id:'w019',name:'Shoulders Beginner Tone',level:'beginner',exercises_count:3,duration:'<10',xp_value:65,target:'shoulders',category:'toning'},
{id:'w020',name:'Quick Fat Burn',level:'beginner',exercises_count:4,duration:'<10',xp_value:75,target:'full body',category:'cardio'},
{id:'w021',name:'Legs & Glutes Shaper',level:'intermediate',exercises_count:5,duration:'15-20',xp_value:140,target:'legs',category:'toning'},
{id:'w022',name:'Back Pro Mastery',level:'pro',exercises_count:4,duration:'20-25',xp_value:280,target:'back',category:'strength'},
{id:'w023',name:'Back & Biceps Blast',level:'advanced',exercises_count:5,duration:'20-25',xp_value:200,target:'back',category:'strength'},
{id:'w024',name:'Legs Explosive Pro',level:'pro',exercises_count:5,duration:'25+',xp_value:310,target:'legs',category:'power'},
{id:'w025',name:'Shoulder Definition Blast',level:'intermediate',exercises_count:5,duration:'15-20',xp_value:130,target:'shoulders',category:'strength'},
{id:'w026',name:'Core Intermediate Shred',level:'intermediate',exercises_count:5,duration:'15-20',xp_value:145,target:'core',category:'strength'},
{id:'w027',name:'Core Beginner Basics',level:'beginner',exercises_count:4,duration:'10-15',xp_value:85,target:'core',category:'strength'},
{id:'w028',name:'Chest Beginner Build',level:'beginner',exercises_count:3,duration:'<10',xp_value:70,target:'chest',category:'strength'},
{id:'w029',name:'Full Body Balance Intermediate',level:'intermediate',exercises_count:6,duration:'25+',xp_value:185,target:'full body',category:'balance'},
{id:'w030',name:'Chest Advanced Power',level:'advanced',exercises_count:4,duration:'15-20',xp_value:180,target:'chest',category:'power'},
{id:'w031',name:'Back Advanced Power',level:'advanced',exercises_count:4,duration:'15-20',xp_value:170,target:'back',category:'power'},
{id:'w032',name:'Arms Pro Domination',level:'pro',exercises_count:5,duration:'25+',xp_value:290,target:'arms',category:'power'},
{id:'w033',name:'Full Body Intermediate Power',level:'intermediate',exercises_count:5,duration:'20-25',xp_value:175,target:'full body',category:'power'},
{id:'w034',name:'Evening Stretch & Tone',level:'beginner',exercises_count:4,duration:'10-15',xp_value:80,target:'full body',category:'flexibility'},
{id:'w035',name:'Legs Pro Explosion',level:'pro',exercises_count:5,duration:'25+',xp_value:300,target:'legs',category:'power'},
{id:'w036',name:'Back & Core Intermediate',level:'intermediate',exercises_count:4,duration:'15-20',xp_value:140,target:'back',category:'strength'},
{id:'w037',name:'Chest Power Pro',level:'pro',exercises_count:5,duration:'25+',xp_value:280,target:'chest',category:'power'},
{id:'w038',name:'Arms Advanced Strength',level:'advanced',exercises_count:4,duration:'15-20',xp_value:175,target:'arms',category:'strength'},
{id:'w039',name:'Beginner Leg Tone',level:'beginner',exercises_count:4,duration:'10-15',xp_value:90,target:'legs',category:'toning'},
{id:'w040',name:'Core Advanced Destroyer',level:'advanced',exercises_count:5,duration:'15-20',xp_value:175,target:'core',category:'strength'},
{id:'w041',name:'Power Strength Advanced',level:'advanced',exercises_count:5,duration:'20-25',xp_value:215,target:'full body',category:'power'},
{id:'w042',name:'Chest Advanced Sculptor',level:'advanced',exercises_count:4,duration:'15-20',xp_value:165,target:'chest',category:'strength'},
{id:'w043',name:'Arms Advanced Pump',level:'advanced',exercises_count:5,duration:'20-25',xp_value:195,target:'arms',category:'strength'},
{id:'w044',name:'Mobility & Flexibility Advanced',level:'advanced',exercises_count:5,duration:'20-25',xp_value:160,target:'full body',category:'flexibility'},
{id:'w045',name:'Core Elite Pro',level:'pro',exercises_count:5,duration:'20-25',xp_value:260,target:'core',category:'strength'},
{id:'w046',name:'Legs Advanced Strength',level:'advanced',exercises_count:5,duration:'20-25',xp_value:195,target:'legs',category:'strength'},
{id:'w047',name:'Shoulders Advanced Burn',level:'advanced',exercises_count:4,duration:'15-20',xp_value:175,target:'shoulders',category:'strength'},
{id:'w048',name:'Endurance Builder Intermediate',level:'intermediate',exercises_count:5,duration:'20-25',xp_value:160,target:'full body',category:'cardio'},
{id:'w049',name:'Core Shred Express',level:'intermediate',exercises_count:7,duration:'10-15',xp_value:120,target:'core',category:'cardio'},
{id:'w050',name:'Abs Intermediate Carve',level:'intermediate',exercises_count:5,duration:'15-20',xp_value:155,target:'core',category:'strength'},
{id:'w051',name:'Post-Workout Cool Down Beginner',level:'beginner',exercises_count:4,duration:'<10',xp_value:55,target:'full body',category:'recovery'},
{id:'w052',name:'Legs Fat Burn Intermediate',level:'intermediate',exercises_count:4,duration:'15-20',xp_value:150,target:'legs',category:'cardio'},
{id:'w053',name:'Shoulders & Legs Intermediate',level:'intermediate',exercises_count:4,duration:'15-20',xp_value:145,target:'shoulders',category:'strength'},
{id:'w054',name:'Full Body Pro Endurance',level:'pro',exercises_count:6,duration:'25+',xp_value:310,target:'full body',category:'cardio'},
{id:'w055',name:'Upper Body Pump Builder',level:'intermediate',exercises_count:6,duration:'15-20',xp_value:150,target:'upper body',category:'strength'},
{id:'w056',name:'Core Advanced Annihilation',level:'advanced',exercises_count:5,duration:'15-20',xp_value:185,target:'core',category:'strength'},
{id:'w057',name:'Active Recovery Intermediate',level:'intermediate',exercises_count:5,duration:'15-20',xp_value:125,target:'full body',category:'recovery'},
{id:'w058',name:'Mobility Flow Beginner',level:'beginner',exercises_count:4,duration:'<10',xp_value:60,target:'full body',category:'mobility'},
{id:'w059',name:'Legs Pro Power',level:'pro',exercises_count:5,duration:'25+',xp_value:305,target:'legs',category:'power'},
{id:'w060',name:'Shoulders Pro Power',level:'pro',exercises_count:4,duration:'20-25',xp_value:275,target:'shoulders',category:'power'},
{id:'w061',name:'Chest Pro Explosion',level:'pro',exercises_count:4,duration:'20-25',xp_value:285,target:'chest',category:'power'},
{id:'w062',name:'Upper Advanced Total',level:'advanced',exercises_count:6,duration:'25+',xp_value:220,target:'upper body',category:'strength'},
{id:'w063',name:'Shoulders Pro Peak',level:'pro',exercises_count:4,duration:'20-25',xp_value:275,target:'shoulders',category:'power'},
{id:'w064',name:'Stretch & Recovery Beginner',level:'beginner',exercises_count:4,duration:'10-15',xp_value:75,target:'full body',category:'recovery'},
{id:'w065',name:'Arms & Chest Intermediate Power',level:'intermediate',exercises_count:4,duration:'15-20',xp_value:145,target:'arms',category:'strength'},
{id:'w066',name:'Legs & Core Beginner',level:'beginner',exercises_count:4,duration:'15-20',xp_value:95,target:'legs',category:'strength'},
{id:'w067',name:'Shoulders & Abs Beginner',level:'beginner',exercises_count:4,duration:'10-15',xp_value:85,target:'shoulders',category:'strength'},
{id:'w068',name:'HIIT Fat Burner Intermediate',level:'intermediate',exercises_count:4,duration:'10-15',xp_value:130,target:'full body',category:'cardio'},
{id:'w069',name:'Total Toning Beginner',level:'beginner',exercises_count:5,duration:'15-20',xp_value:100,target:'full body',category:'toning'},
{id:'w070',name:'Back & Glutes Beginner',level:'beginner',exercises_count:4,duration:'10-15',xp_value:85,target:'back',category:'strength'},
{id:'w071',name:'Chest & Core Beginner',level:'beginner',exercises_count:4,duration:'10-15',xp_value:80,target:'chest',category:'strength'},
{id:'w072',name:'Core Stability Pro',level:'pro',exercises_count:5,duration:'20-25',xp_value:270,target:'core',category:'strength'},
{id:'w073',name:'Quick Lower Body Beginner',level:'beginner',exercises_count:4,duration:'<10',xp_value:70,target:'legs',category:'strength'},
{id:'w074',name:'Total Body Cardio Advanced',level:'advanced',exercises_count:6,duration:'25+',xp_value:225,target:'full body',category:'cardio'},
{id:'w075',name:'Upper Body Beginner Foundation',level:'beginner',exercises_count:4,duration:'15-20',xp_value:95,target:'upper body',category:'strength'},
{id:'w076',name:'Core Fat Burn Intermediate',level:'intermediate',exercises_count:4,duration:'10-15',xp_value:125,target:'core',category:'cardio'},
{id:'w077',name:'Full Body Fat Burn Intermediate',level:'intermediate',exercises_count:5,duration:'20-25',xp_value:170,target:'full body',category:'cardio'},
{id:'w078',name:'Back Advanced Domination',level:'advanced',exercises_count:4,duration:'15-20',xp_value:185,target:'back',category:'strength'},
{id:'w079',name:'Arms Pro Elite',level:'pro',exercises_count:4,duration:'20-25',xp_value:275,target:'arms',category:'power'},
{id:'w080',name:'Back & Shoulders Intermediate',level:'intermediate',exercises_count:5,duration:'20-25',xp_value:165,target:'back',category:'strength'},
{id:'w081',name:'10-Minute Beginner Fat Burn',level:'beginner',exercises_count:8,duration:'<10',xp_value:80,target:'full body',category:'cardio'},
{id:'w082',name:'Pro Athlete Conditioning',level:'pro',exercises_count:7,duration:'25+',xp_value:300,target:'full body',category:'conditioning'},
{id:'w083',name:'Full Body Cardio Blast',level:'intermediate',exercises_count:5,duration:'15-20',xp_value:150,target:'full body',category:'cardio'},
{id:'w084',name:'Core & Cardio Intermediate',level:'intermediate',exercises_count:4,duration:'15-20',xp_value:140,target:'core',category:'cardio'},
{id:'w085',name:'Chest & Shoulders Intermediate',level:'intermediate',exercises_count:4,duration:'15-20',xp_value:135,target:'chest',category:'strength'},
{id:'w086',name:'Core Pro Mastery',level:'pro',exercises_count:4,duration:'20-25',xp_value:265,target:'core',category:'strength'},
{id:'w087',name:'Leg Day Power Circuit',level:'advanced',exercises_count:7,duration:'20-25',xp_value:200,target:'legs',category:'circuit'},
{id:'w088',name:'Back Domination Pro',level:'pro',exercises_count:5,duration:'25+',xp_value:290,target:'back',category:'power'},
{id:'w089',name:'Shoulders Advanced Build',level:'advanced',exercises_count:4,duration:'15-20',xp_value:160,target:'shoulders',category:'strength'},
{id:'w090',name:'Back Pro Strength',level:'pro',exercises_count:4,duration:'20-25',xp_value:280,target:'back',category:'strength'},
{id:'w091',name:'Explosive Power Pro',level:'pro',exercises_count:6,duration:'25+',xp_value:330,target:'full body',category:'power'},
{id:'w092',name:'Full Body Quick Tone',level:'beginner',exercises_count:4,duration:'<10',xp_value:70,target:'full body',category:'toning'},
{id:'w093',name:'Chest Pro Supreme',level:'pro',exercises_count:4,duration:'20-25',xp_value:270,target:'chest',category:'power'},
{id:'w094',name:'Full Body Athlete Builder',level:'advanced',exercises_count:8,duration:'25+',xp_value:220,target:'full body',category:'conditioning'},
{id:'w095',name:'Arms Intermediate Pump',level:'intermediate',exercises_count:5,duration:'20-25',xp_value:170,target:'arms',category:'strength'},
{id:'w096',name:'Morning Energy Boost',level:'beginner',exercises_count:4,duration:'<10',xp_value:65,target:'full body',category:'energy'},
{id:'w097',name:'Chest & Triceps Burner',level:'advanced',exercises_count:5,duration:'20-25',xp_value:190,target:'chest',category:'strength'},
{id:'w098',name:'Full Body Advanced Athlete',level:'advanced',exercises_count:6,duration:'25+',xp_value:230,target:'full body',category:'conditioning'},
{id:'w099',name:'Legs & Glutes Intermediate Power',level:'intermediate',exercises_count:5,duration:'20-25',xp_value:170,target:'legs',category:'strength'},
{id:'w100',name:'Back Beginner Strengthen',level:'beginner',exercises_count:3,duration:'<10',xp_value:70,target:'back',category:'strength'},
{id:'w101',name:'Glutes & Hamstrings Advanced',level:'advanced',exercises_count:5,duration:'20-25',xp_value:205,target:'legs',category:'strength'},
{id:'w102',name:'Quick Arms Tone',level:'beginner',exercises_count:4,duration:'<10',xp_value:65,target:'arms',category:'toning'},
{id:'w103',name:'Full Body Advanced HIIT',level:'advanced',exercises_count:6,duration:'25+',xp_value:225,target:'full body',category:'cardio'},
{id:'w104',name:'Quick Core Stabilizer',level:'beginner',exercises_count:4,duration:'<10',xp_value:70,target:'core',category:'strength'}
];

const quickStartWorkouts=[
{name:'Morning Cricket Warm-Up',level:'beginner',target:'full body',goal:'keep fit',duration_category:'<10',xp_value:65,is_premium:false,exercises:[{name:'Jumping Jacks',sets:2,reps:20,rest_seconds:30},{name:'Arm Circles',sets:2,reps:15,rest_seconds:20},{name:'Hip Rotations',sets:2,reps:10,rest_seconds:20},{name:'High Knees',sets:2,reps:20,rest_seconds:30}]},
{name:'Batting Power Builder',level:'intermediate',target:'arms',goal:'build muscle',duration_category:'15-20',xp_value:145,is_premium:false,exercises:[{name:'Push-Ups',sets:3,reps:15,rest_seconds:45},{name:'Tricep Dips',sets:3,reps:12,rest_seconds:45},{name:'Wrist Curls',sets:3,reps:20,rest_seconds:30},{name:'Forearm Plank Hold',sets:3,reps:30,rest_seconds:45}]},
{name:'Bowler Shoulder Circuit',level:'intermediate',target:'shoulders',goal:'build muscle',duration_category:'15-20',xp_value:140,is_premium:false,exercises:[{name:'Band Pull-Aparts',sets:3,reps:15,rest_seconds:30},{name:'Face Pulls',sets:3,reps:12,rest_seconds:30},{name:'External Rotations',sets:3,reps:15,rest_seconds:30},{name:'Lateral Raises',sets:3,reps:12,rest_seconds:45}]},
{name:'Fielder Agility Blast',level:'intermediate',target:'legs',goal:'keep fit',duration_category:'10-15',xp_value:130,is_premium:false,exercises:[{name:'Lateral Shuffles',sets:3,reps:10,rest_seconds:30},{name:'Sprint & Stop',sets:4,reps:5,rest_seconds:45},{name:'Squat Jumps',sets:3,reps:10,rest_seconds:45},{name:'Direction Changes',sets:3,reps:8,rest_seconds:30}]},
{name:'Core Stability for Cricket',level:'beginner',target:'core',goal:'keep fit',duration_category:'10-15',xp_value:90,is_premium:false,exercises:[{name:'Plank Hold',sets:3,reps:30,rest_seconds:30},{name:'Dead Bug',sets:3,reps:10,rest_seconds:30},{name:'Bird Dog',sets:3,reps:10,rest_seconds:30},{name:'Glute Bridge',sets:3,reps:15,rest_seconds:30}]},
{name:'Explosive Leg Day',level:'advanced',target:'legs',goal:'build muscle',duration_category:'20-25',xp_value:200,is_premium:false,exercises:[{name:'Box Jumps',sets:4,reps:8,rest_seconds:60},{name:'Jump Squats',sets:3,reps:10,rest_seconds:60},{name:'Bulgarian Split Squats',sets:3,reps:10,rest_seconds:60},{name:'Single Leg Bounds',sets:3,reps:6,rest_seconds:60},{name:'Sprint Starts',sets:5,reps:1,rest_seconds:45}]},
{name:'Quick HIIT Fat Burn',level:'intermediate',target:'full body',goal:'lose weight',duration_category:'<10',xp_value:100,is_premium:false,exercises:[{name:'Burpees',sets:3,reps:10,rest_seconds:20},{name:'Mountain Climbers',sets:3,reps:20,rest_seconds:20},{name:'High Knees',sets:3,reps:30,rest_seconds:20},{name:'Jump Lunges',sets:3,reps:10,rest_seconds:20}]},
{name:'Upper Body Endurance',level:'intermediate',target:'upper body',goal:'keep fit',duration_category:'15-20',xp_value:150,is_premium:false,exercises:[{name:'Push-Up Variations',sets:4,reps:15,rest_seconds:30},{name:'Superman Hold',sets:3,reps:10,rest_seconds:30},{name:'Shoulder Taps',sets:3,reps:20,rest_seconds:30},{name:'Tricep Push-Ups',sets:3,reps:12,rest_seconds:30}]},
{name:'Wicketkeeper Power',level:'intermediate',target:'legs',goal:'build muscle',duration_category:'15-20',xp_value:155,is_premium:false,exercises:[{name:'Deep Squat Hold',sets:3,reps:10,rest_seconds:30},{name:'Lateral Lunges',sets:3,reps:12,rest_seconds:30},{name:'Calf Raises',sets:3,reps:20,rest_seconds:20},{name:'Squat Jumps',sets:3,reps:8,rest_seconds:45}]},
{name:'Full Body Cricket Conditioning',level:'advanced',target:'full body',goal:'keep fit',duration_category:'20-25',xp_value:210,is_premium:false,exercises:[{name:'Burpees',sets:4,reps:10,rest_seconds:30},{name:'Pull-Up Simulation',sets:3,reps:12,rest_seconds:45},{name:'Box Jumps',sets:3,reps:8,rest_seconds:45},{name:'Plank to Push-Up',sets:3,reps:10,rest_seconds:30},{name:'Sprint Drill',sets:5,reps:1,rest_seconds:30}]},
{name:'Beginner Strength Foundation',level:'beginner',target:'full body',goal:'build muscle',duration_category:'15-20',xp_value:100,is_premium:false,exercises:[{name:'Wall Push-Ups',sets:3,reps:15,rest_seconds:30},{name:'Chair Squats',sets:3,reps:15,rest_seconds:30},{name:'Plank Hold',sets:3,reps:20,rest_seconds:30},{name:'Glute Bridge',sets:3,reps:15,rest_seconds:30}]},
{name:'Pro Athlete Power',level:'pro',target:'full body',goal:'build muscle',duration_category:'25+',xp_value:320,is_premium:true,exercises:[{name:'Plyometric Push-Ups',sets:5,reps:8,rest_seconds:60},{name:'Pistol Squat Progressions',sets:4,reps:6,rest_seconds:90},{name:'Explosive Pull-Ups',sets:4,reps:6,rest_seconds:90},{name:'Sprint Intervals',sets:8,reps:1,rest_seconds:30},{name:'L-Sit Practice',sets:3,reps:10,rest_seconds:60}]},
{name:'Spine & Posture Restore',level:'beginner',target:'back',goal:'keep fit',duration_category:'10-15',xp_value:80,is_premium:false,exercises:[{name:'Cat-Cow Stretch',sets:3,reps:10,rest_seconds:15},{name:'Childs Pose',sets:3,reps:30,rest_seconds:15},{name:'Cobra Pose',sets:3,reps:10,rest_seconds:15},{name:'Thoracic Rotations',sets:2,reps:15,rest_seconds:20}]},
{name:'Pre-Match Activation',level:'beginner',target:'full body',goal:'keep fit',duration_category:'<10',xp_value:65,is_premium:false,exercises:[{name:'Dynamic Stretches',sets:2,reps:10,rest_seconds:15},{name:'Ankle Rotations',sets:2,reps:15,rest_seconds:10},{name:'Hip Flexor Activation',sets:2,reps:10,rest_seconds:15},{name:'Shoulder Warm-Up Circles',sets:2,reps:15,rest_seconds:10}]},
{name:'Posterior Chain Power',level:'advanced',target:'back',goal:'build muscle',duration_category:'20-25',xp_value:195,is_premium:false,exercises:[{name:'Deadlift BW',sets:4,reps:12,rest_seconds:60},{name:'Good Mornings',sets:3,reps:12,rest_seconds:45},{name:'Reverse Hypers',sets:3,reps:15,rest_seconds:45},{name:'Superman Hold',sets:3,reps:15,rest_seconds:30}]},
{name:'Shoulder Longevity',level:'beginner',target:'shoulders',goal:'keep fit',duration_category:'10-15',xp_value:75,is_premium:false,exercises:[{name:'Pendulum Swings',sets:2,reps:20,rest_seconds:20},{name:'Wall Slides',sets:3,reps:12,rest_seconds:20},{name:'Band Face Pulls',sets:3,reps:15,rest_seconds:20},{name:'Cross-Body Shoulder Stretch',sets:2,reps:30,rest_seconds:15}]},
{name:'Sprint Speed Development',level:'intermediate',target:'legs',goal:'keep fit',duration_category:'15-20',xp_value:155,is_premium:false,exercises:[{name:'A-Skip Drills',sets:3,reps:20,rest_seconds:45},{name:'B-Skip Drills',sets:3,reps:20,rest_seconds:45},{name:'Running Arms Drill',sets:3,reps:20,rest_seconds:30},{name:'Acceleration Sprints 20m',sets:6,reps:1,rest_seconds:60}]},
{name:'Core Rotation Power',level:'intermediate',target:'core',goal:'build muscle',duration_category:'15-20',xp_value:145,is_premium:false,exercises:[{name:'Russian Twists',sets:3,reps:20,rest_seconds:30},{name:'Woodchops',sets:3,reps:12,rest_seconds:30},{name:'Side Plank Rotation',sets:3,reps:10,rest_seconds:30},{name:'Pallof Press BW',sets:3,reps:12,rest_seconds:30}]},
{name:'Total Body Fat Torch',level:'advanced',target:'full body',goal:'lose weight',duration_category:'20-25',xp_value:215,is_premium:false,exercises:[{name:'Burpee Box Jumps',sets:4,reps:8,rest_seconds:30},{name:'Sprint 30m',sets:6,reps:1,rest_seconds:30},{name:'Jump Lunges',sets:4,reps:12,rest_seconds:30},{name:'Mountain Climbers Fast',sets:4,reps:30,rest_seconds:20}]},
{name:'Balance & Proprioception',level:'beginner',target:'legs',goal:'keep fit',duration_category:'10-15',xp_value:85,is_premium:false,exercises:[{name:'Single Leg Stand',sets:3,reps:30,rest_seconds:20},{name:'Eyes Closed Balance',sets:3,reps:20,rest_seconds:20},{name:'Tandem Walk',sets:3,reps:10,rest_seconds:20},{name:'Single Leg Reach',sets:3,reps:10,rest_seconds:20}]},
{name:'Arm Endurance Circuit',level:'intermediate',target:'arms',goal:'keep fit',duration_category:'10-15',xp_value:120,is_premium:false,exercises:[{name:'Push-Ups Max',sets:4,reps:20,rest_seconds:30},{name:'Tricep Dips',sets:4,reps:15,rest_seconds:30},{name:'Diamond Push-Ups',sets:3,reps:12,rest_seconds:30},{name:'Plank Hold',sets:3,reps:30,rest_seconds:20}]},
{name:'Elite Conditioning Circuit',level:'pro',target:'full body',goal:'keep fit',duration_category:'25+',xp_value:310,is_premium:true,exercises:[{name:'Plyometric Lunges',sets:4,reps:12,rest_seconds:60},{name:'Sprint Pyramid',sets:5,reps:1,rest_seconds:45},{name:'Clapping Push-Ups',sets:4,reps:8,rest_seconds:60},{name:'Tuck Jumps',sets:4,reps:10,rest_seconds:45}]},
{name:'Lower Body Stretch',level:'beginner',target:'legs',goal:'keep fit',duration_category:'<10',xp_value:60,is_premium:false,exercises:[{name:'Quad Stretch',sets:2,reps:30,rest_seconds:10},{name:'Hamstring Stretch',sets:2,reps:30,rest_seconds:10},{name:'Hip Flexor Lunge',sets:2,reps:30,rest_seconds:10},{name:'Calf Stretch',sets:2,reps:30,rest_seconds:10}]},
{name:'Chest & Back Superset',level:'intermediate',target:'chest',goal:'build muscle',duration_category:'15-20',xp_value:150,is_premium:false,exercises:[{name:'Push-Ups',sets:4,reps:15,rest_seconds:30},{name:'Superman Hold',sets:4,reps:15,rest_seconds:30},{name:'Wide Push-Ups',sets:3,reps:12,rest_seconds:30},{name:'Back Extension',sets:3,reps:15,rest_seconds:30}]},
{name:'Game Ready Warm-Up',level:'beginner',target:'full body',goal:'keep fit',duration_category:'<10',xp_value:60,is_premium:false,exercises:[{name:'Jog in Place',sets:1,reps:60,rest_seconds:10},{name:'Arm Swings',sets:2,reps:20,rest_seconds:10},{name:'Leg Swings',sets:2,reps:15,rest_seconds:10},{name:'Torso Twists',sets:2,reps:20,rest_seconds:10}]},
{name:'Power Endurance Advanced',level:'advanced',target:'full body',goal:'keep fit',duration_category:'20-25',xp_value:210,is_premium:false,exercises:[{name:'10m Sprint Repeats',sets:8,reps:1,rest_seconds:20},{name:'Burpees',sets:4,reps:10,rest_seconds:20},{name:'Box Step-Ups Fast',sets:4,reps:12,rest_seconds:20},{name:'Plyo Push-Ups',sets:3,reps:8,rest_seconds:30},{name:'Jump Squats',sets:4,reps:10,rest_seconds:20}]},
{name:'Glute Activation',level:'beginner',target:'legs',goal:'build muscle',duration_category:'<10',xp_value:70,is_premium:false,exercises:[{name:'Clamshells',sets:3,reps:15,rest_seconds:20},{name:'Glute Bridge',sets:3,reps:20,rest_seconds:20},{name:'Donkey Kicks',sets:3,reps:15,rest_seconds:20},{name:'Fire Hydrants',sets:3,reps:15,rest_seconds:20}]},
{name:'Cricket Strength & Power',level:'advanced',target:'full body',goal:'build muscle',duration_category:'25+',xp_value:225,is_premium:false,exercises:[{name:'Single Leg Squat',sets:4,reps:8,rest_seconds:60},{name:'Explosive Push-Ups',sets:4,reps:10,rest_seconds:60},{name:'Nordic Hamstring Curls',sets:3,reps:6,rest_seconds:90},{name:'Sprint Bounds',sets:5,reps:8,rest_seconds:60},{name:'Core Anti-Rotation',sets:3,reps:12,rest_seconds:45}]},
{name:'Desk Cricketer Relief',level:'beginner',target:'full body',goal:'keep fit',duration_category:'<10',xp_value:55,is_premium:false,exercises:[{name:'Neck Rolls',sets:2,reps:10,rest_seconds:10},{name:'Chest Opener Stretch',sets:2,reps:30,rest_seconds:10},{name:'Hip Flexor Stretch',sets:2,reps:30,rest_seconds:10},{name:'Wrist Mobility',sets:2,reps:15,rest_seconds:10}]},
{name:'Interval Sprint Series',level:'intermediate',target:'legs',goal:'lose weight',duration_category:'15-20',xp_value:160,is_premium:false,exercises:[{name:'30m Sprint',sets:6,reps:1,rest_seconds:60},{name:'Walk Recovery',sets:6,reps:1,rest_seconds:60},{name:'Bounding',sets:4,reps:10,rest_seconds:45},{name:'High Knees Fast',sets:4,reps:30,rest_seconds:30}]},
{name:'Shoulder Health Protocol',level:'intermediate',target:'shoulders',goal:'keep fit',duration_category:'15-20',xp_value:130,is_premium:false,exercises:[{name:'YTW Exercise',sets:3,reps:10,rest_seconds:30},{name:'Band External Rotation',sets:3,reps:15,rest_seconds:30},{name:'Wall Slides',sets:3,reps:12,rest_seconds:30},{name:'Prone T Exercise',sets:3,reps:12,rest_seconds:30}]},
{name:'Knee Stability Builder',level:'beginner',target:'legs',goal:'keep fit',duration_category:'10-15',xp_value:80,is_premium:false,exercises:[{name:'Wall Sit Hold',sets:3,reps:30,rest_seconds:30},{name:'Terminal Knee Extension',sets:3,reps:15,rest_seconds:20},{name:'Straight Leg Raise',sets:3,reps:15,rest_seconds:20},{name:'Step-Ups',sets:3,reps:12,rest_seconds:30}]},
{name:'Advanced HIIT Finisher',level:'advanced',target:'full body',goal:'lose weight',duration_category:'10-15',xp_value:175,is_premium:false,exercises:[{name:'Tabata Burpees',sets:8,reps:8,rest_seconds:10},{name:'Tabata Mountain Climbers',sets:8,reps:20,rest_seconds:10},{name:'Sprint 20m',sets:5,reps:1,rest_seconds:15}]},
{name:'Upper Body Volume Day',level:'intermediate',target:'upper body',goal:'build muscle',duration_category:'20-25',xp_value:170,is_premium:false,exercises:[{name:'Push-Up Max Sets',sets:5,reps:15,rest_seconds:30},{name:'Pike Push-Ups',sets:4,reps:10,rest_seconds:30},{name:'Dips',sets:4,reps:12,rest_seconds:30},{name:'Plank Shoulder Taps',sets:3,reps:20,rest_seconds:30}]},
{name:'Mobility Master Class',level:'intermediate',target:'full body',goal:'keep fit',duration_category:'15-20',xp_value:140,is_premium:false,exercises:[{name:'Worlds Greatest Stretch',sets:3,reps:8,rest_seconds:15},{name:'90 90 Hip Rotation',sets:3,reps:10,rest_seconds:15},{name:'Thoracic Spine Rotation',sets:3,reps:12,rest_seconds:15},{name:'Deep Squat Hold',sets:3,reps:30,rest_seconds:20}]},
{name:'Pro Power Sprint Series',level:'pro',target:'legs',goal:'keep fit',duration_category:'20-25',xp_value:285,is_premium:true,exercises:[{name:'Flying 30s Sprint',sets:6,reps:1,rest_seconds:120},{name:'Wicket Runs Simulation',sets:5,reps:4,rest_seconds:60},{name:'Resisted Sprints',sets:4,reps:1,rest_seconds:90},{name:'Depth Jump to Sprint',sets:4,reps:3,rest_seconds:90}]},
{name:'Core Comprehensive',level:'intermediate',target:'core',goal:'build muscle',duration_category:'15-20',xp_value:145,is_premium:false,exercises:[{name:'Plank Hold',sets:3,reps:45,rest_seconds:30},{name:'Side Plank',sets:3,reps:30,rest_seconds:30},{name:'V-Ups',sets:3,reps:12,rest_seconds:30},{name:'Flutter Kicks',sets:3,reps:30,rest_seconds:30},{name:'Russian Twists',sets:3,reps:20,rest_seconds:30}]},
{name:'Active Recovery Flow',level:'beginner',target:'full body',goal:'keep fit',duration_category:'10-15',xp_value:75,is_premium:false,exercises:[{name:'Light Walking',sets:1,reps:120,rest_seconds:0},{name:'Gentle Yoga Stretches',sets:3,reps:30,rest_seconds:10},{name:'Deep Breathing',sets:3,reps:10,rest_seconds:10}]},
{name:'Plyometric Power Dev',level:'advanced',target:'legs',goal:'build muscle',duration_category:'20-25',xp_value:205,is_premium:false,exercises:[{name:'Depth Jumps',sets:4,reps:6,rest_seconds:90},{name:'Broad Jumps',sets:4,reps:6,rest_seconds:60},{name:'Single Leg Hops',sets:3,reps:8,rest_seconds:60},{name:'Reactive Sprint',sets:5,reps:1,rest_seconds:45}]},
{name:'Neck & Trap Strength',level:'beginner',target:'back',goal:'keep fit',duration_category:'<10',xp_value:60,is_premium:false,exercises:[{name:'Neck Isometrics',sets:3,reps:10,rest_seconds:15},{name:'Shrug Hold',sets:3,reps:10,rest_seconds:15},{name:'Upper Trap Stretch',sets:2,reps:30,rest_seconds:10},{name:'Chin Tucks',sets:3,reps:12,rest_seconds:10}]},
{name:'Functional Movement Screen',level:'beginner',target:'full body',goal:'keep fit',duration_category:'10-15',xp_value:70,is_premium:false,exercises:[{name:'Overhead Squat',sets:2,reps:10,rest_seconds:20},{name:'Hurdle Step Simulation',sets:2,reps:10,rest_seconds:20},{name:'In-Line Lunge',sets:2,reps:10,rest_seconds:20},{name:'Shoulder Mobility Test',sets:2,reps:5,rest_seconds:15}]},
{name:'Hamstring & Glute Focus',level:'intermediate',target:'legs',goal:'build muscle',duration_category:'15-20',xp_value:155,is_premium:false,exercises:[{name:'Romanian Deadlift BW',sets:4,reps:12,rest_seconds:45},{name:'Glute Bridge Marching',sets:3,reps:15,rest_seconds:30},{name:'Nordic Curl Negatives',sets:3,reps:6,rest_seconds:90},{name:'Step-Up & Drive',sets:3,reps:10,rest_seconds:30}]},
{name:'Wrist & Forearm Strength',level:'beginner',target:'arms',goal:'build muscle',duration_category:'<10',xp_value:65,is_premium:false,exercises:[{name:'Wrist Curls',sets:3,reps:20,rest_seconds:20},{name:'Reverse Wrist Curls',sets:3,reps:20,rest_seconds:20},{name:'Grip Squeeze',sets:3,reps:30,rest_seconds:15},{name:'Finger Extensions',sets:3,reps:15,rest_seconds:15}]},
{name:'Cross-Training Triathlon',level:'advanced',target:'full body',goal:'keep fit',duration_category:'25+',xp_value:220,is_premium:false,exercises:[{name:'1km Run Pace',sets:1,reps:1,rest_seconds:120},{name:'50 Push-Ups',sets:1,reps:50,rest_seconds:60},{name:'50 Squats',sets:1,reps:50,rest_seconds:60},{name:'2min Plank',sets:1,reps:120,rest_seconds:60},{name:'Sprint Finish 200m',sets:1,reps:1,rest_seconds:0}]},
{name:'Power Up Morning Routine',level:'intermediate',target:'full body',goal:'keep fit',duration_category:'10-15',xp_value:125,is_premium:false,exercises:[{name:'Jumping Jacks',sets:3,reps:20,rest_seconds:15},{name:'Push-Ups',sets:3,reps:12,rest_seconds:20},{name:'Bodyweight Squats',sets:3,reps:15,rest_seconds:20},{name:'Plank Hold',sets:3,reps:30,rest_seconds:15}]},
{name:'Cricket Sprints & Recovery',level:'intermediate',target:'legs',goal:'keep fit',duration_category:'15-20',xp_value:150,is_premium:false,exercises:[{name:'22-yard Pitch Sprint',sets:8,reps:1,rest_seconds:30},{name:'Walk Back Recovery',sets:8,reps:1,rest_seconds:30},{name:'Lateral Shuffle 5m',sets:4,reps:10,rest_seconds:20}]}
];

const skillPathsDb={
  batting:{id:'sp_batting',title:'Batting Mastery',description:'Master all aspects of cricket batting',icon:'Target',color:'from-blue-500 to-indigo-600',
    levels:[
      {level:1,title:'Stance & Grip',xp_required:0,drills:['d001','d003','d006']},
      {level:2,title:'Basic Shots',xp_required:200,drills:['d001','d003','d041','d009']},
      {level:3,title:'Rotation & Running',xp_required:500,drills:['d009','d056','d057']},
      {level:4,title:'Power Hitting',xp_required:1000,drills:['d002','d039','d040']},
      {level:5,title:'Advanced Technique',xp_required:2000,drills:['d007','d010','d051','d052']}
    ]},
  bowling:{id:'sp_bowling',title:'Bowling Excellence',description:'Develop pace swing spin and variation',icon:'Zap',color:'from-emerald-500 to-teal-600',
    levels:[
      {level:1,title:'Action & Run-Up',xp_required:0,drills:['d018','d055','d046']},
      {level:2,title:'Swing & Seam',xp_required:200,drills:['d011','d012','d046']},
      {level:3,title:'Line & Length',xp_required:500,drills:['d015','d018','d045']},
      {level:4,title:'Variations',xp_required:1000,drills:['d016','d019','d059']},
      {level:5,title:'Death Bowling',xp_required:2000,drills:['d015','d020','d047']}
    ]},
  fielding:{id:'sp_fielding',title:'Fielding Brilliance',description:'Become an elite fielder',icon:'Shield',color:'from-orange-500 to-red-600',
    levels:[
      {level:1,title:'Ground Fielding',xp_required:0,drills:['d021','d053','d027']},
      {level:2,title:'Throwing',xp_required:150,drills:['d024','d028']},
      {level:3,title:'Catching',xp_required:350,drills:['d022','d025','d058']},
      {level:4,title:'Boundary Fielding',xp_required:700,drills:['d023','d026','d054']},
      {level:5,title:'Elite Fielder',xp_required:1500,drills:['d023','d024','d025','d028']}
    ]},
  mental:{id:'sp_mental',title:'Mental Strength',description:'Build the mental game of champions',icon:'Brain',color:'from-purple-500 to-pink-600',
    levels:[
      {level:1,title:'Foundations',xp_required:0,drills:['d037','d049','d038']},
      {level:2,title:'Focus',xp_required:200,drills:['d036','d037','d038']},
      {level:3,title:'Pressure',xp_required:500,drills:['d036','d050']},
      {level:4,title:'Visualization',xp_required:1000,drills:['d037','d050']},
      {level:5,title:'Elite Mindset',xp_required:2000,drills:['d036','d037','d038','d049','d050']}
    ]}
};

return {jokes,facts,drills,mentalRoutines,workouts,quickStartWorkouts,skillPathsDb};
})();
